config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :playlists, only: [:index, :new, :create, :show, :destroy, :edit] do
    resources :songs, only: [:index, :new, :show, :create, :destroy]
  end

  root 'welcome#index'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  post '/playlists/:id' => 'playlists#add_user'

end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  has_many :users
  has_many :songs
end

app/models/song.rb
require 'open-uri'

class Song < ActiveRecord::Base
  belongs_to :playlist

  def song_search
    name_formatted = name.gsub(/\s/, '+')
    artist_formatted = artist.gsub(/\s/, '+')
    name_formatted + '+' + artist_formatted
  end

  def in_spotify?
    data = JSON.load(open('https://api.spotify.com/v1/search?q=' + song_search + '&type=track'))
    return false if data['tracks']['items'].empty?
    true
  end

  def spotify_uri
    data = JSON.load(open('https://api.spotify.com/v1/search?q=' + song_search + '&type=track'))
    return nil if data['tracks']['items'].empty?
    data['tracks']['items'][1]['uri']
  end
end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base
  include BCrypt

  has_many :playlists
  belongs_to :playlist
  validates :name, presence: :true, uniqueness: true, length: { minimum: 2 }
  validates :bio, presence: :true, length: { minimum: 1 }

  def password
    @password ||= Password.new(password_hash) if password_hash
  end

  def password=(new_password)
    @password = Password.create(new_password)
    self.password_hash = @password
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method def logged_in?
    session[:user_id]
  end

  helper_method def current_user
    @current_user ||= User.find(session[:user_id]) if logged_in?
  end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  def new
    @playlist = Playlist.new
  end

  def create
    @playlist = Playlist.create(name: playlist_params[:name])
    @playlist.users << current_user
    current_user.playlists << @playlist
    if @playlist.save
      redirect_to current_user
    else
      render :new
    end
  end

  def show
    @playlist = Playlist.find(params[:id])
  end

  def edit
    @playlist = Playlist.find(params[:id])
  end

  def update
    @playlist = Playlist.find(params[:id])
    if @playlist.update(playlist_params)
      redirect_to current_user, notice: 'playlist was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    Playlist.find(params[:id]).destroy
    redirect_to current_user, notice: 'playlist was successfully destroyed.'
  end

  def add_user
    @playlist = Playlist.find(params[:id])
    @playlist.users << current_user
    current_user.playlists << @playlist
    redirect_to "/playlists/#{@playlist.id}"
  end

  # Only allow a trusted parameter "white list" through.
  def playlist_params
    params.require(:playlist).permit(:name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(name: params[:name])
    if @user && @user.password == params[:password]
      session[:user_id] = @user.id
      redirect_to @user
    else
      redirect_to '/login'
    end
  end

  def destroy
    reset_session
    redirect_to root_path
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def new
    @song = Song.new
    @song.playlist = Playlist.find(params[:playlist_id])
  end

  def create
    @song = Song.new(name: song_params[:name], artist: song_params[:artist])
    @song.playlist = Playlist.find(params[:playlist_id])
    if @song.in_spotify?
      @song.save
      @song.playlist.songs << @song
      redirect_to "/playlists/#{params[:playlist_id]}"
    else
      redirect_to new_playlist_song_path, notice: 'song was not in spotify'
    end
  end

  def show
    @song = Song.find(params[:id])
  end

  def destroy
    Song.find(params[:id]).destroy
    redirect_to "/playlists/#{params[:playlist_id]}", notice: 'song was successfully destroyed.'
  end

  def song_params
    params.require(:song).permit(:name, :artist)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action only: [:show, :edit, :update, :destroy]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  def create
    @user = User.new(user_params)
    @user.password = user_params[:password]
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    reset_session
    redirect_to '/users', notice: 'User was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def user_params
    params.require(:user).permit(:name, :bio, :password)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_nav.html.erb
<nav class="nav-banner">
  <a class="nav-btn" href="/">HOME</a>
  <a class="nav-btn" href="/users">USERS</a>
  <% if logged_in? %>
    <%= link_to current_user.name, "/users/#{current_user.id}", class: "nav-btn" %>
    <%= link_to 'LOG OUT', '/logout', method: :delete, class: "nav-btn" %>
  <% end %>
  
  <span class="nav-sessions">
  </span>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cis196Project</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/nav' %>

<%= yield %>

</body>
</html>

app/views/playlists/_form.html.erb
<div>
  <%= form_for(@playlist) do |f| %>

    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <br>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/playlists/new.html.erb
<h1>New Playlist</h1>

<%= render 'form' %>

app/views/playlists/show.html.erb
<p id="notice"><%= notice %></p>
<h1 class="green"> Playlist: <%= @playlist.name %> </h1>

<h2> Playlist Owners: </h2>
<% User.all.each do |user| %>
  <% if (@playlist.users.include? user) || (user.playlists.include? @playlist) %>
    <tr>
      <td><%= user.name %></td>
    </tr>
    <br>
  <% end %>
<% end %>
<br>

<h2> Songs in Playlist </h2>
<% @playlist.songs.each do |song| %>
  <tr>
  	<td><%= song.name %> by <%= song.artist %></td>
  	<td><%= link_to 'Play', "/playlists/#{@playlist.id}/songs/#{song.id}" %></td>
  	<td><%= link_to 'Delete', "/playlists/#{@playlist.id}/songs/#{song.id}", method: :delete, data: { confirm: 'Are you sure?' } %></td>
  	<br>
  </tr>
<% end %>

<% if @playlist.users.include? current_user %>
  <h4> <%= link_to 'Add song to playlist', "/playlists/#{@playlist.id}/songs/new"%> </h4>
<% end %>

app/views/songs/_form.html.erb
<div>
  <%= form_for([@song.playlist, @song]) do |f| %>

    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <br>
    <div class="artist">
      <%= f.label :artist %><br>
      <%= f.text_field :artist %>
    </div>
    <br>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/songs/new.html.erb
<h1> Add song to playlist </h1>

<%= render 'form' %>

app/views/songs/show.html.erb
<div>
	</br>
	<p id="notice"><%= notice %></p>

	<h2 class="green">
	  <strong>Song:</strong>
	  <%= @song.name %>
	</h2>

	<h2>
	  <strong>Artist:</strong>
	  <%= @song.artist %>
	</h2>
	<br>

	<iframe src="https://embed.spotify.com/?uri=<%=@song.spotify_uri%>" width="300" height="380" frameborder="0" allowtransparency="true"></iframe><br>

	<h3>Playlists Containing This Song:</h3>
	<% Playlist.all.each do |playlist| %>
      <% playlist.songs.each do |s| %>
        <% if s.name.eql? @song.name %>
          <%= playlist.name %>
          <br>
        <% end %>
      <% end %>
    <% end %>
    <br>

	<footer>
		<%= link_to 'Back', "/playlists/#{params[:playlist_id]}" %>
	</footer>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <br>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <br>
  <div class="field">
    <%= f.label :bio %><br>
    <%= f.text_field :bio %>
  </div>
  <br>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>
<h4>Re-enter original password before editing<h4>
<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="green">All Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td class="green"><%= user.name %></td>
        <td><%= link_to 'Visit Page', user %>
        <% if user ==  current_user %>
          <span> | </span>
          <td><%= link_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path, class: "user-btn" %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<h1 class="green"><%= @user.name %></h1>
<span id="bio">Bio:</span> <%= @user.bio %>
<h3>Playlists</h3>
<% Playlist.all.each do |playlist| %>
  <% if (playlist.users.include? @user) || (@user.playlists.include? playlist) %>
    <tr>
      <td><%= playlist.name %></td>
      <td><%= link_to 'Show', "/playlists/#{playlist.id}" %></td>
      <% if @user ==  current_user %>
        <td><%= link_to 'Delete', "/playlists/#{playlist.id}", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
      <% if logged_in? %>
        <td><%= link_to 'Join Playlist', "/playlists/#{playlist.id}", method: :post %></td>
      <% end %>
      <br>
    </tr>
  <% end %>
<% end %>
<br>
<br>
<% if logged_in? && @user == current_user %>
  <%= link_to 'New Playlist |', new_playlist_path(@user.id), class: "user-btn" %>
  <%= link_to 'Edit User |', edit_user_path(@user), class: "user-btn" %>
  <%= link_to 'Delete', @user, method: :delete, data: { confirm: 'Are you sure?' }, class: "user-btn" %>
<% end %>

<br>
<br>

<%= link_to 'Back', users_path, class: "user-btn" %>

app/views/welcome/index.html.erb
<h1 id="title">S P O T I F Y</h1>
<%= image_tag('spotify-logo.png', :class => "logo") %>
<br>
<% unless logged_in? %>
  <%= link_to 'Log in', '/login', class: "home-btn" %>
  <%= link_to 'Sign up', '/users/new', class: "home-btn" %>
<% end %>